/* tslint:disable */
/* eslint-disable */
/*
 * Autogenerated by @creditkarma/thrift-typescript v3.7.6
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
*/
import * as thrift from "thrift";
export interface IAddressArgs {
    country?: string;
    city?: string;
    street?: string;
    zip?: number;
}
export class Address {
    public country?: string;
    public city?: string;
    public street?: string;
    public zip?: number;
    constructor(args?: IAddressArgs) {
        if (args != null && args.country != null) {
            this.country = args.country;
        }
        if (args != null && args.city != null) {
            this.city = args.city;
        }
        if (args != null && args.street != null) {
            this.street = args.street;
        }
        if (args != null && args.zip != null) {
            this.zip = args.zip;
        }
    }
    public write(output: thrift.TProtocol): void {
        output.writeStructBegin("Address");
        if (this.country != null) {
            output.writeFieldBegin("country", thrift.Thrift.Type.STRING, 1);
            output.writeString(this.country);
            output.writeFieldEnd();
        }
        if (this.city != null) {
            output.writeFieldBegin("city", thrift.Thrift.Type.STRING, 2);
            output.writeString(this.city);
            output.writeFieldEnd();
        }
        if (this.street != null) {
            output.writeFieldBegin("street", thrift.Thrift.Type.STRING, 3);
            output.writeString(this.street);
            output.writeFieldEnd();
        }
        if (this.zip != null) {
            output.writeFieldBegin("zip", thrift.Thrift.Type.I32, 4);
            output.writeI32(this.zip);
            output.writeFieldEnd();
        }
        output.writeFieldStop();
        output.writeStructEnd();
        return;
    }
    public static read(input: thrift.TProtocol): Address {
        input.readStructBegin();
        let _args: any = {};
        while (true) {
            const ret: thrift.TField = input.readFieldBegin();
            const fieldType: thrift.Thrift.Type = ret.ftype;
            const fieldId: number = ret.fid;
            if (fieldType === thrift.Thrift.Type.STOP) {
                break;
            }
            switch (fieldId) {
                case 1:
                    if (fieldType === thrift.Thrift.Type.STRING) {
                        const value_1: string = input.readString();
                        _args.country = value_1;
                    }
                    else {
                        input.skip(fieldType);
                    }
                    break;
                case 2:
                    if (fieldType === thrift.Thrift.Type.STRING) {
                        const value_2: string = input.readString();
                        _args.city = value_2;
                    }
                    else {
                        input.skip(fieldType);
                    }
                    break;
                case 3:
                    if (fieldType === thrift.Thrift.Type.STRING) {
                        const value_3: string = input.readString();
                        _args.street = value_3;
                    }
                    else {
                        input.skip(fieldType);
                    }
                    break;
                case 4:
                    if (fieldType === thrift.Thrift.Type.I32) {
                        const value_4: number = input.readI32();
                        _args.zip = value_4;
                    }
                    else {
                        input.skip(fieldType);
                    }
                    break;
                default: {
                    input.skip(fieldType);
                }
            }
            input.readFieldEnd();
        }
        input.readStructEnd();
        return new Address(_args);
    }
}
